### ISSUE TITLE
create agent without whitelist?

### ISSUE THREAD

**Issue by y-ang2010** [Psychedelic/plug#228]
Hello,  my team develop app on ic , deside to use plug. Our app have many canisters ,and it will keep increasing . 

There will be too many operations for  add whitelist on create a agent. Is there a way to approve all canister whitout use whitelist ?

<img src="https://user-images.githubusercontent.com/12936750/134307606-dfc581af-ddff-4842-9fb1-80efbe8fd0d5.png" height="50%" width="50%">

**Comment by kanej** [comment]
That is a great question and one we are exploring ourselves. Can you go into more detail on your use case?

Are canister's being added dynamically during the user's session?

**Comment by y-ang2010** [comment]
Yes . Our canister will added dynamically during the session.

**Comment by tomiir** [comment]
@y-ang2010 Hi! 
How do you feel about the security aspect of it? Because letting an app interact with ANY canister without the user knowing seems a little bit risky to me. 
The way I imagine an implementation for this use case is something like 
- Allowing the `whitelist` param to receive a wildcard ('*') and that would allow any connection.
- Each time a request to sign a message is sent, confirmation is asked from the user.

I think the signature confirmation (at least) is necessary. Else a lot of things are going on under the hood, which could definetly be malicious and the user would never realize about it.

**Comment by y-ang2010** [comment]
@tomiir 
I agree with your point for  'allowing the whitelist param use wildcard ('*')'.   It will be a good way.

Bu on dfinity ic network,  every request should sign. So i don't think confirmation each sign message is a good option. 

![image](https://user-images.githubusercontent.com/12936750/134448065-92fa391b-26ef-4f8a-9764-f85e63008b9c.png)

**Comment by tomiir** [comment]
Sorry about the delay, the new canister should be added to the whitelist. Does the issue persist? Else I'll create a ticket for this. @y-ang2010

**Comment by riveign** [comment]
@y-ang2010 any comments on @tomiir reply?

**Comment by riveign** [comment]
Closing this issue due to innactivity
